### ISSUE TITLE
Unable to Resolve Module (config) via Screen Component

### ISSUE THREAD

**Issue by JosephSemrai** [scorelab/park#17]
**Describe the bug**
The application, created by following the developer guide on Elly, throws an error upon trying to load the login/initial screen as a result of loading `FormScreen`. This component tries to load a config file two directories up that does not resolve correctly (doesn't exist in some configurations). With this, Elly had a similar issue, leading me to believe that there may be a missing step in the developer guide or an issue with using the Android 10.0 API (v29).

**To Reproduce**
1. Build development version of the app
2. Launch development server
3. Open Parks app in an Android 9.0 or 10.0 virtual device (Android 9.0 using Intel API)

**Expected behavior**
Login form to be displayed

**Screenshots**
Error Logs:
![qemu-system-x86_64_ttnPqE2rQ2](https://user-images.githubusercontent.com/29003194/71709578-08a49600-2dc6-11ea-9c94-8795643ce927.png)

**Smartphone (please complete the following information):**
 - Device: Virtual Nexus 5X (running API 29 x86)
 - OS: Tested on Android 10.0 and 9.0
 - Browser: Not Relevant
 - Version: Google APIs 29

**Additional context**
Google Services: com.dwc

**Comment by AsithaIndrajith** [comment]
Sorry for the delay. This issue is related to not having config.js file. You can follow the 6th step in the contribution.md.
